// Generated by https://quicktype.io

import { OperatorEntity } from "App/Operator/domain/entities";


export interface DocumentResponse {
    _id?:                    string;
    name?:                   string;
    client?:                 string;
    status?:                 boolean;
    minBet?:                 number;
    maxBet?:                 number;
    endpointAuth?:           string;
    endpointBet?:            string;
    endpointWin?:            string;
    endpointRollback?:       string;
    casinoToken?:            string;
    available?:              boolean;
    uuid?:                   string;
    operatorId?:             number;
    chips?:                  string[];
    games?:                  string[];
    currencies?:             string[];
    gamesPayments?:          any[];
    limits?:                 any[];
    isoCode?:                string;
    usdRateChange?:          number;
    exchangeRateHistory?:    any[];
    useLogo?:                boolean;
    value?:                  number;
    color?:                  any;
    createdAt?:              string;
    updatedAt?:              string;
    userId?:                 string;
    username?:               string;
    lastBalance?:            number;
    isAdmin?:                boolean;
    tokenWallet?:            string;
    WL?:                     string;
    currencyUuid?:           string;
    operator?:               OperatorEntity
};
