// Generated by https://quicktype.io

export interface PlayerWalletResponse {
    ok:                boolean;
    mensaje:           string;
    userId:            number;
    username:          string;
    lastBalance:       string;
    country_code:      string;
    email:             string;
    last_name:         string;
    currency:          string;
    available_balance: string;
    WL?:               string;
    msg?:              string;
}
